In [1]:
import pandas as pd

## Read Meta-dataset and dataset meta-features

In [3]:
# read metadataset
metadataset_df = pd.read_csv("../TabSurvey/metadataset_v0.csv")

In [4]:
metadataset_df.head()

,results_bucket_path,dataset_fold_id,dataset_name,alg_name,hparam_source,trial_number,alg_hparam_id,exp_name,time__train,Log Loss__train,...,AUC__test,Accuracy__test,F1__test,time__train-eval,MSE__train,R2__train,MSE__val,R2__val,MSE__test,R2__test
0,results/openml__APSFailure__168868/CatBoost/gp...,openml__APSFailure__168868__fold_0,openml__APSFailure__168868,CatBoost,default,0,CatBoost__seed_0__trial_0,gpu-expt-a_091822_065111_fdd9.zip,4.039096,0.018501,...,0.994533,0.993421,0.993421,0.185535,NaN,NaN,NaN,NaN,NaN,NaN
1,results/openml__APSFailure__168868/CatBoost/gp...,openml__APSFailure__168868__fold_0,openml__APSFailure__168868,CatBoost,random_1_s0,1,CatBoost__seed_0__trial_1,gpu-expt-a_091822_065111_fdd9.zip,3.624039,0.011968,...,0.995148,0.994605,0.994605,0.129900,NaN,NaN,NaN,NaN,NaN,NaN
2,results/openml__APSFailure__168868/CatBoost/gp...,openml__APSFailure__168868__fold_0,openml__APSFailure__168868,CatBoost,random_10_s0,10,CatBoost__seed_0__trial_10,gpu-expt-a_091822_065111_fdd9.zip,2.494685,0.022589,...,0.993307,0.990921,0.990921,0.074099,NaN,NaN,NaN,NaN,NaN,NaN
3,results/openml__APSFailure__168868/CatBoost/gp...,openml__APSFailure__168868__fold_0,openml__APSFailure__168868,CatBoost,random_11_s0,11,CatBoost__seed_0__trial_11,gpu-expt-a_091822_065111_fdd9.zip,2.532277,0.028515,...,0.989220,0.990132,0.990132,0.061874,NaN,NaN,NaN,NaN,NaN,NaN
4,results/openml__APSFailure__168868/CatBoost/gp...,openml__APSFailure__168868__fold_0,openml__APSFailure__168868,CatBoost,random_12_s0,12,CatBoost__seed_0__trial_12,gpu-expt-a_091822_065111_fdd9.zip,4.220030,0.015119,...,0.994578,0.993684,0.993684,0.121606,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# read dataset metafeatures
metafeatures_df = pd.read_csv("../TabSurvey/metafeatures.csv")

In [6]:
metafeatures_df.head()

,dataset_name,f__pymfe.landmarking.best_node.count,f__pymfe.landmarking.best_node.count.relative,f__pymfe.landmarking.best_node.histogram.0,f__pymfe.landmarking.best_node.histogram.0.relative,f__pymfe.landmarking.best_node.histogram.1,f__pymfe.landmarking.best_node.histogram.1.relative,f__pymfe.landmarking.best_node.histogram.2,f__pymfe.landmarking.best_node.histogram.2.relative,f__pymfe.landmarking.best_node.histogram.3,...,f__pymfe.relative.worst_node.quantiles.4,f__pymfe.relative.worst_node.quantiles.4.relative,f__pymfe.relative.worst_node.range,f__pymfe.relative.worst_node.range.relative,f__pymfe.relative.worst_node.sd,f__pymfe.relative.worst_node.sd.relative,f__pymfe.relative.worst_node.skewness,f__pymfe.relative.worst_node.skewness.relative,f__pymfe.statistical.iq_range,f__pymfe.statistical.t_mean
0,openml__pc4__3902__fold_0,10,4.0,0.0,2.0,0.0,4.0,0.0,2.5,0.0,...,0.5,2.0,0.0,2.0,0.0,2.0,NaN,7.0,NaN,NaN
1,openml__pc4__3902__fold_1,10,4.0,0.8,7.0,0.0,3.5,0.0,2.0,0.0,...,0.5,1.5,0.0,1.5,0.0,1.5,NaN,7.0,NaN,NaN
2,openml__pc4__3902__fold_2,10,4.0,0.8,7.0,0.0,3.0,0.0,3.0,0.0,...,0.5,1.5,0.0,1.5,0.0,1.5,NaN,7.0,NaN,NaN
3,openml__pc4__3902__fold_3,10,4.0,0.0,2.0,0.0,3.5,0.0,2.5,0.0,...,0.5,2.0,0.0,2.0,0.0,2.0,NaN,7.0,NaN,NaN
4,openml__pc4__3902__fold_4,10,4.0,0.0,2.0,0.0,3.0,0.0,3.0,0.0,...,0.5,2.0,0.0,2.0,0.0,2.0,NaN,7.0,NaN,NaN

In [7]:
# check whether all datasets in the meta-dataset are represented in the metafeatures
all_datasets_metadata = metadataset_df["dataset_fold_id"].unique()
all_datasets_metafeatures = metafeatures_df["dataset_name"].unique()

# all datasets without metafeatures - this set should be empty
datasets_without_metafeatures = set(all_datasets_metadata) - set(all_datasets_metafeatures)
print(f"there are {len(datasets_without_metafeatures)} datasets without metafeatures...")
if len(datasets_without_metafeatures) > 0:
    print(f"datasets_without_metafeatures: {datasets_without_metafeatures}")

there are 60 datasets without metafeatures...
datasets_without_metafeatures: {'openml__mv__4774__fold_3', 'openml__sulfur__360966__fold_1', 'openml__colleges__359942__fold_1', 'openml__Bank-Note-Authentication-UCI__361002__fold_4', 'openml__veteran__4828__fold_6', 'openml__sulfur__360966__fold_3', 'openml__sulfur__360966__fold_7', 'openml__sulfur__360966__fold_2', 'openml__colleges__359942__fold_2', 'openml__Bank-Note-Authentication-UCI__361002__fold_0', 'openml__california__361089__fold_1', 'openml__california__361089__fold_7', 'openml__colleges__359942__fold_5', 'openml__mv__4774__fold_1', 'openml__Bank-Note-Authentication-UCI__361002__fold_7', 'openml__Bank-Note-Authentication-UCI__361002__fold_1', 'openml__sulfur__360966__fold_4', 'openml__sulfur__360966__fold_0', 'openml__veteran__4828__fold_3', 'openml__california__361089__fold_4', 'openml__colleges__359942__fold_9', 'openml__mv__4774__fold_0', 'openml__Bank-Note-Authentication-UCI__361002__fold_9', 'openml__Bank-Note-Authentication-UCI__361002__fold_3', 'openml__sulfur__360966__fold_9', 'openml__sulfur__360966__fold_5', 'openml__mv__4774__fold_4', 'openml__california__361089__fold_9', 'openml__mv__4774__fold_6', 'openml__veteran__4828__fold_0', 'openml__veteran__4828__fold_8', 'openml__colleges__359942__fold_6', 'openml__mv__4774__fold_2', 'openml__sulfur__360966__fold_6', 'openml__veteran__4828__fold_1', 'openml__Bank-Note-Authentication-UCI__361002__fold_6', 'openml__veteran__4828__fold_2', 'openml__Bank-Note-Authentication-UCI__361002__fold_8', 'openml__veteran__4828__fold_5', 'openml__veteran__4828__fold_4', 'openml__colleges__359942__fold_4', 'openml__california__361089__fold_0', 'openml__Bank-Note-Authentication-UCI__361002__fold_2', 'openml__colleges__359942__fold_8', 'openml__colleges__359942__fold_0', 'openml__mv__4774__fold_9', 'openml__california__361089__fold_2', 'openml__california__361089__fold_8', 'openml__colleges__359942__fold_7', 'openml__colleges__359942__fold_3', 'openml__mv__4774__fold_8', 'openml__sulfur__360966__fold_8', 'openml__mv__4774__fold_5', 'openml__veteran__4828__fold_9', 'openml__mv__4774__fold_7', 'openml__Bank-Note-Authentication-UCI__361002__fold_5', 'openml__california__361089__fold_3', 'openml__california__361089__fold_6', 'openml__california__361089__fold_5', 'openml__veteran__4828__fold_7'}

## Quick look at results

In [48]:
# how many algs?
print(f"total number of algs: {len(metadataset_df['alg_name'].unique())}:")
print(metadataset_df.groupby("alg_name")["dataset_name"].count().rename("num_results").reset_index())

# how many datasets?
print(f"total number of datasets: {len(metadataset_df['dataset_name'].unique())}:")
print(metadataset_df.groupby("dataset_name")["dataset_name"].count().rename("num_results").reset_index())

# keep only linear model results with default params (there are no hparams...)
metadataset_df = metadataset_df.loc[~((metadataset_df["alg_name"] == "LinearModel") & (metadataset_df["hparam_source"].str.contains("random"))), :]

total number of algs: 7:
      alg_name  num_results
0     CatBoost        30900
1          KNN        29800
2  LinearModel        31620
3          MLP        31620
4          SVM        17800
5       TabNet        17830
6      XGBoost        32740
total number of datasets: 113:
                                         dataset_name  num_results
0                          openml__APSFailure__168868         1270
1               openml__Amazon_employee_access__34539         1500
2                          openml__Australian__146818         2100
3        openml__Bank-Note-Authentication-UCI__361002         1500
4                           openml__Bioresponse__9910         2100
5                            openml__CIFAR_10__167124          550
6                    openml__Devnagari-Script__167121          240
7                       openml__Fashion-MNIST__146825          890
8    openml__GesturePhaseSegmentationProcessed__14969         1750
9             openml__Internet-Advertisements__167125         1910
10                        openml__MiceProtein__146800         2100
11                          openml__MiniBooNE__168335         1160
12                    openml__PhishingWebsites__14952         1960
13                         openml__adult-census__3953         1690
14                                openml__adult__7592         1600
15                           openml__airlines__189354         1260
16                             openml__albert__189356          970
17               openml__analcatdata_authorship__3549         2100
18                     openml__analcatdata_dmft__3560         2100
19                              openml__arrhythmia__5         1500
20                          openml__balance-scale__11         2100
21                      openml__bank-marketing__14965         1540
22                       openml__bank-marketing__9899         1500
23             openml__banknote-authentication__10093         2100
24    openml__blood-transfusion-service-center__10101         2080
25   openml__blood-transfusion-service-center__145836         1500
26                      openml__breast-cancer__145799         1500
27                               openml__breast-w__15         2100
28                         openml__california__361089         1700
29                                openml__car__146821         2100
..                                                ...          ...
83                                  openml__pc3__3903         2100
84                                  openml__pc4__3902         2100
85                              openml__pendigits__32         1670
86                         openml__philippine__190410         1500
87                              openml__phoneme__9952         1850
88                      openml__primary-tumor__146032         1500
89                          openml__qsar-biodeg__9957         2100
90                           openml__riccardo__168338          840
91                             openml__robert__168332          730
92                             openml__satimage__2074         2040
93                            openml__segment__146822         2100
94                              openml__semeion__9964         2100
95                            openml__shuttle__146212         1390
96                                 openml__sick__3021         2060
97                    openml__skin-segmentation__9965         1270
98                                openml__soybean__41         1500
99                               openml__spambase__43         2030
100                                openml__splice__45         2100
101                openml__steel-plates-fault__146817         2030
102                            openml__sulfur__360966         1500
103                           openml__sylvine__168912         1200
104                           openml__texture__125922         2060
105                           openml__tic-tac-toe__49         2100
106                               openml__vehicle__53         2100
107                             openml__veteran__4828         1500
108                           openml__volkert__168331         1280
109                               openml__vowel__3022         2100
110               openml__wall-robot-navigation__9960         2100
111                                openml__wdbc__9946         2100
112                              openml__wilt__146820         2080

[113 rows x 2 columns]

### Average metrics over all folds

In [49]:
# add column that shows the alg + hparam source
metadataset_df.loc[:, "alg_hparam_source"] = metadataset_df.apply(lambda row: row["alg_name"] + "_" + row["hparam_source"], axis=1)

In [50]:
# for each metric, average over all folds
metric_list = [
    "time",
    "Log Loss",
    "AUC",
    "Accuracy",
    "F1",
    "MSE",
    "R2",
]

fold_list = ["train", "val", "test"]

import itertools
all_metrics = [m + "__" + f for m, f in itertools.product(metric_list, fold_list)]

agg_dict = {metric: ["mean", "max", "min"] for metric in all_metrics}
agg_dict["dataset_name"] = "count"

# for each alg+hparam_source and dataset name, find the average over all folds
agg_metrics = metadataset_df.groupby(["alg_name", "hparam_source", "dataset_name"]).agg(agg_dict).reset_index()

In [51]:
# only look at results where mean log-loss is not NaN 
agg_metrics_ll = agg_metrics.loc[~agg_metrics["Log Loss__val"]["mean"].isna(), :]

# add more informative column names
new_cols = []
for l0, l1 in zip(agg_metrics_ll.columns.get_level_values(0), agg_metrics_ll.columns.get_level_values(1)):
    if l1 == '':
        new_col = l0
    else:
        new_col = l0 + "__" + l1
    new_cols.append(new_col)

agg_metrics_ll.columns = new_cols

agg_metrics_ll.head()

,alg_name,hparam_source,dataset_name,time__train__mean,time__train__max,time__train__min,time__val__mean,time__val__max,time__val__min,time__test__mean,...,R2__train__mean,R2__train__max,R2__train__min,R2__val__mean,R2__val__max,R2__val__min,R2__test__mean,R2__test__max,R2__test__min,dataset_name__count
0,CatBoost,default,openml__APSFailure__168868,2.933755,4.039096,2.737015,0.018531,0.028121,0.016983,0.017852,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
1,CatBoost,default,openml__Amazon_employee_access__34539,1.703913,2.475985,1.537286,0.036080,0.042608,0.029944,0.034669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
2,CatBoost,default,openml__Australian__146818,1.307000,2.204476,1.185732,0.001908,0.003949,0.001090,0.001861,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
4,CatBoost,default,openml__Bioresponse__9910,2.595033,3.435146,2.332858,0.043804,0.050988,0.036083,0.042060,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10
5,CatBoost,default,openml__Fashion-MNIST__146825,10.195699,10.392159,10.086459,0.100702,0.107928,0.089128,0.101606,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10

In [52]:
# since we want to minimize log-loss, we "optimize" hyperparameters for each alg + dataset by taking the hparam row the min (mean) ll :
metric_name = "Log Loss__val__mean"
best_metrics_alg_dataset = agg_metrics_ll.groupby(["alg_name", "dataset_name"])[metric_name].min().rename(metric_name).reset_index()

In [53]:
# merge in the best (lowest mean) log-loss for each alg/dataset
best_rows_ll = best_metrics_alg_dataset.merge(agg_metrics_ll, on=["alg_name", "dataset_name", metric_name], how="inner")

In [59]:
# how many rows per dataset/alg? there should be only one...
count_rows = best_rows_ll.groupby(["alg_name", "dataset_name"])["dataset_name"].count().sort_values(ascending=False)

count_rows[count_rows > 1]

alg_name  dataset_name
KNN       openml__har__14970                                  4
          openml__dilbert__168909                             4
          openml__pendigits__32                               4
          openml__texture__125922                             4
          openml__sick__3021                                  3
          openml__helena__168329                              3
          openml__isolet__3481                                3
          openml__jasmine__168911                             3
          openml__eye_movements__3897                         3
          openml__wilt__146820                                3
          openml__wdbc__9946                                  3
          openml__wall-robot-navigation__9960                 3
          openml__credit-approval__29                         3
          openml__covertype__7593                             3
          openml__christine__168908                           3
          openml__house_16H__3686                             3
          openml__steel-plates-fault__146817                  3
          openml__Australian__146818                          3
          openml__Bioresponse__9910                           3
          openml__bank-marketing__9899                        3
          openml__ozone-level-8hr__9978                       3
          openml__analcatdata_authorship__3549                3
          openml__philippine__190410                          3
          openml__nomao__9977                                 3
          openml__GesturePhaseSegmentationProcessed__14969    3
          openml__MiceProtein__146800                         2
          openml__first-order-theorem-proving__9985           2
          openml__blood-transfusion-service-center__10101     2
          openml__eucalyptus__2079                            2
          openml__electricity__219                            2
          openml__analcatdata_dmft__3560                      2
          openml__banknote-authentication__10093              2
          openml__breast-cancer__145799                       2
          openml__blood-transfusion-service-center__145836    2
          openml__dresses-sales__125920                       2
          openml__ilpd__9971                                  2
          openml__mfeat-morphological__18                     2
          openml__vowel__3022                                 2
          openml__mfeat-fourier__14                           2
          openml__kc1__3917                                   2
          openml__sylvine__168912                             2
          openml__jm1__3904                                   2
          openml__pc3__3903                                   2
          openml__mfeat-zernike__22                           2
          openml__mfeat-factors__12                           2
Name: dataset_name, dtype: int64

In [62]:
# # oops.. let's look at the cases with 30..
# best_rows_ll.loc[(best_rows_ll["alg_name"] == "KNN") & (best_rows_ll["dataset_name"] == "openml__har__14970"), :]

# because we don't care about hparams now, let's keep only the first row for each alg+dataset
best_rows_ll.drop_duplicates(subset=["alg_name", "dataset_name"], keep="first", inplace=True)
best_rows_ll.groupby(["alg_name", "dataset_name"])["dataset_name"].count().max()

1

### Compare Algs for a given dataset

In [66]:
# how many algs for each dataset?
best_rows_ll.groupby(["dataset_name"])["alg_name"].count().sort_values(ascending=False)

dataset_name
openml__wilt__146820                                      7
openml__mfeat-zernike__22                                 7
openml__mfeat-karhunen__16                                7
openml__climate-model-simulation-crashes__146819          7
openml__mfeat-factors__12                                 7
openml__madelon__9976                                     7
openml__letter__6                                         7
openml__kr-vs-kp__3                                       7
openml__kc2__3913                                         7
openml__kc1__3917                                         7
openml__analcatdata_authorship__3549                      7
openml__jm1__3904                                         7
openml__analcatdata_dmft__3560                            7
openml__ilpd__9971                                        7
openml__balance-scale__11                                 7
openml__wdbc__9946                                        7
openml__har__14970                                        7
openml__banknote-authentication__10093                    7
openml__blood-transfusion-service-center__10101           7
openml__first-order-theorem-proving__9985                 7
openml__eucalyptus__2079                                  7
openml__breast-w__15                                      7
openml__car__146821                                       7
openml__dresses-sales__125920                             7
openml__dna__167140                                       7
openml__diabetes__37                                      7
openml__cylinder-bands__14954                             7
openml__credit-g__31                                      7
openml__credit-approval__29                               7
openml__churn__167141                                     7
                                                         ..
openml__mnist_784__3573                                   5
openml__shuttle__146212                                   5
openml__primary-tumor__146032                             5
openml__philippine__190410                                5
openml__numerai28.6__167120                               5
openml__dilbert__168909                                   5
openml__volkert__168331                                   5
openml__jungle_chess_2pcs_raw_endgame_complete__167119    5
openml__jasmine__168911                                   5
openml__jannis__168330                                    5
openml__house_16H__3686                                   5
openml__haberman__42                                      5
openml__soybean__41                                       5
openml__gas-drift-different-concentrations__9987          5
openml__fabert__168910                                    5
openml__eye_movements__3897                               5
openml__eeg-eye-state__14951                              5
openml__ecoli__145977                                     5
openml__skin-segmentation__9965                           5
openml__CIFAR_10__167124                                  4
openml__Fashion-MNIST__146825                             4
openml__albert__189356                                    4
openml__higgs__146606                                     4
openml__sylvine__168912                                   4
openml__robert__168332                                    3
openml__riccardo__168338                                  3
openml__Devnagari-Script__167121                          3
openml__guillermo__168337                                 3
openml__covertype__7593                                   2
openml__helena__168329                                    2
Name: alg_name, Length: 107, dtype: int64

There are not a ton of results yet. Let's only look at datasets with at least 5 algs...

In [74]:
best_rows_ll.loc[:, "rank_" + metric_name] = best_rows_ll.groupby("dataset_name")[metric_name].rank(method="min", ascending=True).values
# # get the rank of each alg within each dataset, for each metric
# for metric in metric_list:
#     # rank within dataset
#     df_expt.loc[:, "rank_" + metric] = df_expt.groupby([dataset_col])["normalized_" + metric].rank(method="min", ascending=False).values

In [96]:
keep_cols = [
    "alg_name",
    "dataset_name", 
    "hparam_source",
] + [c for c in best_rows_ll.columns if "time" in c] + [c for c in best_rows_ll.columns if metric_name in c]

ll_results = best_rows_ll.loc[:, keep_cols]
len(ll_results)

646

In [97]:
# let's sanity-check a single dataset
ll_results.loc[ll_results["dataset_name"] == "openml__har__14970", :]

,alg_name,dataset_name,hparam_source,time__train__mean,time__train__max,time__train__min,time__val__mean,time__val__max,time__val__min,time__test__mean,time__test__max,time__test__min,Log Loss__val__mean,rank_Log Loss__val__mean
48,CatBoost,openml__har__14970,random_25_s0,5.227615,5.271920,5.154176,0.033144,0.035605,0.030349,0.033062,0.034004,0.032209,0.065085,5.0
175,KNN,openml__har__14970,default,2.172085,2.934382,0.974432,19.525691,21.698339,17.339096,19.718446,21.259604,18.987894,0.119938,7.0
318,LinearModel,openml__har__14970,default,0.242050,0.357859,0.112605,0.016965,0.032142,0.008142,0.013140,0.037997,0.007333,0.056469,4.0
421,MLP,openml__har__14970,random_22_s0,31.658422,31.810428,31.397744,0.062752,0.066011,0.060800,0.062027,0.063403,0.059983,0.083601,6.0
502,SVM,openml__har__14970,random_6_s0,33.725928,37.133684,30.788649,1.680794,1.900425,1.542598,1.705354,1.920871,1.544722,0.028050,2.0
574,TabNet,openml__har__14970,random_8_s0,154.149007,230.937029,95.887107,0.131542,0.134394,0.127936,0.131819,0.137530,0.127742,0.032422,3.0
666,XGBoost,openml__har__14970,random_27_s0,3.350301,3.459303,3.292270,0.039040,0.049287,0.034739,0.038584,0.053205,0.033792,0.021898,1.0

### Analyze Results for log-loss

In [98]:
# For each alg, find the best, worst, and mean rank, over all datasets.
# here, count = the number of datasets for which we have results for the alg. 
ll_results.groupby("alg_name").agg({"rank_" + metric_name: ["mean", "max", "min", "count"]})

            rank_Log Loss__val__mean
                                mean  max  min count
alg_name
CatBoost                    2.463918  6.0  1.0    97
KNN                         5.316327  7.0  1.0    98
LinearModel                 4.850000  7.0  2.0   100
MLP                         4.433962  7.0  1.0   106
SVM                         3.484848  7.0  1.0    66
TabNet                      2.567568  7.0  1.0    74
XGBoost                     2.161905  6.0  1.0   105

In [99]:
# calculate normalized ll for each result, such that norm(ll) = 0 for the best algorithm, and 1 for the worst, on each dataset.
min_metric = ll_results.groupby("dataset_name")[metric_name].min().rename("min_metric_on_dataset")
max_metric = ll_results.groupby("dataset_name")[metric_name].max().rename("max_metric_on_dataset")

ll_results = ll_results.merge(min_metric, on="dataset_name").merge(max_metric, on="dataset_name")
ll_results.loc[:, "normalized_metric"] = (ll_results[metric_name].values - ll_results["min_metric_on_dataset"].values) / ( ll_results["max_metric_on_dataset"].values -  ll_results["min_metric_on_dataset"].values)

In [101]:
# sanity check again
ll_results.loc[ll_results["dataset_name"] == "openml__har__14970", :]

,alg_name,dataset_name,hparam_source,time__train__mean,time__train__max,time__train__min,time__val__mean,time__val__max,time__val__min,time__test__mean,time__test__max,time__test__min,Log Loss__val__mean,rank_Log Loss__val__mean,min_metric_on_dataset,max_metric_on_dataset,normalized_metric
295,CatBoost,openml__har__14970,random_25_s0,5.227615,5.271920,5.154176,0.033144,0.035605,0.030349,0.033062,0.034004,0.032209,0.065085,5.0,0.021898,0.119938,0.440500
296,KNN,openml__har__14970,default,2.172085,2.934382,0.974432,19.525691,21.698339,17.339096,19.718446,21.259604,18.987894,0.119938,7.0,0.021898,0.119938,1.000000
297,LinearModel,openml__har__14970,default,0.242050,0.357859,0.112605,0.016965,0.032142,0.008142,0.013140,0.037997,0.007333,0.056469,4.0,0.021898,0.119938,0.352621
298,MLP,openml__har__14970,random_22_s0,31.658422,31.810428,31.397744,0.062752,0.066011,0.060800,0.062027,0.063403,0.059983,0.083601,6.0,0.021898,0.119938,0.629361
299,SVM,openml__har__14970,random_6_s0,33.725928,37.133684,30.788649,1.680794,1.900425,1.542598,1.705354,1.920871,1.544722,0.028050,2.0,0.021898,0.119938,0.062747
300,TabNet,openml__har__14970,random_8_s0,154.149007,230.937029,95.887107,0.131542,0.134394,0.127936,0.131819,0.137530,0.127742,0.032422,3.0,0.021898,0.119938,0.107343
301,XGBoost,openml__har__14970,random_27_s0,3.350301,3.459303,3.292270,0.039040,0.049287,0.034739,0.038584,0.053205,0.033792,0.021898,1.0,0.021898,0.119938,0.000000

In [102]:
# For each alg, find the best, worst, and mean **normalized metric, over all datasets.
# here, count = the number of datasets for which we have results for the alg. 
# and 0 = best (min) 1 = worst (max)
ll_results.groupby("alg_name").agg({"normalized_metric": ["mean", "max", "min", "count"]})

            normalized_metric
                         mean       max       min count
alg_name
CatBoost             0.108022  0.820013  0.000000    97
KNN                  0.613953  1.000000  0.000000    98
LinearModel          0.529956  1.000000  0.000793   100
MLP                  0.614315  1.000000  0.000000   106
SVM                  0.257852  1.000000  0.000000    66
TabNet               0.112868  1.000000  0.000000    74
XGBoost              0.099493  0.938602  0.000000   105

## Merge Metafeatures into Results

In [77]:
# TBD